version: '3'
services:
  php-fpm:
    build:
      context: ./docker/php-fpm
    volumes:
      - ./src:/var/www
  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./src:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"

  database:
    restart: always
    build:
      context: ./docker/database
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=hello
      - MYSQL_PASSWORD=pass
      - MYSQL_ROOT_PASSWORD=docker
    volumes:
      - ./docker/database/data.sql:/docker-entrypoint-initdb.d/data.sql
